/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/list/fill copy.vue')['default']
    Delete: typeof import('./src/components/list/delete.vue')['default']
    Fill: typeof import('./src/components/list/fill.vue')['default']
    Fixed: typeof import('./src/components/list/fixed.vue')['default']
    Group: typeof import('./src/components/function/group/group.vue')['default']
    List: typeof import('./src/components/list/list.vue')['default']
    Menu: typeof import('./src/components/common/menu.vue')['default']
    Resize: typeof import('./src/components/list/resize.vue')['default']
    Size: typeof import('./src/components/function/resize/size.vue')['default']
    Skeleton: typeof import('./src/components/skeleton.vue')['default']
    Sort: typeof import('./src/components/list/sort.vue')['default']
    Table: typeof import('./src/components/list/table.vue')['default']
  }
}
