/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/common/Alert.vue')['default']
    CellFill: typeof import('./src/components/layout/list/CellFill.vue')['default']
    CellWrap: typeof import('./src/components/layout/list/CellWrap.vue')['default']
    ColumnAggs: typeof import('./src/components/layout/list/ColumnAggs.vue')['default']
    ColumnCopy: typeof import('./src/components/layout/list/ColumnCopy.vue')['default']
    ColumnDelete: typeof import('./src/components/layout/list/ColumnDelete.vue')['default']
    ColumnDict: typeof import('./src/components/layout/list/ColumnDict.vue')['default']
    ColumnFixed: typeof import('./src/components/layout/list/ColumnFixed.vue')['default']
    ColumnHide: typeof import('./src/components/layout/list/ColumnHide.vue')['default']
    ColumnMore: typeof import('./src/components/layout/list/ColumnMore.vue')['default']
    ColumnRename: typeof import('./src/components/layout/list/ColumnRename.vue')['default']
    ColumnResize: typeof import('./src/components/layout/list/ColumnResize.vue')['default']
    ColumnSort: typeof import('./src/components/layout/list/ColumnSort.vue')['default']
    copy: typeof import('./src/components/layout/list/Rows copy.vue')['default']
    Filter: typeof import('./src/components/function/Filter.vue')['default']
    Group: typeof import('./src/components/function/Group.vue')['default']
    Header: typeof import('./src/components/layout/list/Header.vue')['default']
    IconPicker: typeof import('./src/components/common/IconPicker.vue')['default']
    List: typeof import('./src/components/layout/list/List.vue')['default']
    Menu: typeof import('./src/components/common/Menu.vue')['default']
    Resize: typeof import('./src/components/function/Resize.vue')['default']
    RowDelete: typeof import('./src/components/layout/list/RowDelete.vue')['default']
    Rows: typeof import('./src/components/layout/list/Rows.vue')['default']
    RowSelect: typeof import('./src/components/layout/list/RowSelect.vue')['default']
    RowSort: typeof import('./src/components/function/RowSort.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    Theme: typeof import('./src/components/function/Theme.vue')['default']
  }
}
