// https://primer.style/foundations/icons

export const TEXT = 'octicon-file-24'
export const TEXTAREA = 'octicon-file-code-24'
export const NUMBER = 'octicon-list-ordered-24'
export const BOOLEAN = 'octicon-checklist-24'
export const FILE = 'octicon-file-zip-24'
export const IMAGE = 'octicon-image-24'
export const SELECT = 'octicon-single-select-24'
export const MULTISELECT = 'octicon-multi-select-24'
export const CHECKBOX = 'octicon-checkbox-24'
export const DATE = 'octicon-calendar-24'
export const DATETIME = 'octicon-calendar-24'
export const TIME = 'octicon-clock-24'
export const EMAIL = 'octicon-mail-24'
export const AMOUNT = 'octicon-credit-card-24'
export const URL = 'octicon-link-24'
export const PHONE = 'octicon-device-mobile-24'
export const PASSWORD = 'octicon-passkey-fill-24'

export const CHART = 'octicon-graph-24'
export const LIST = 'octicon-list-unordered-24'
export const CALENDAR = 'octicon-calendar-24'
export const KANBAN = 'octicon-project-24'
export const GANTT = 'octicon-workflow-24'

export const NEW = 'octicon-plus-24'
export const DELETE = 'octicon-x-24'
export const RESET = 'octicon-issue-tracked-by-24'
export const HIDE = 'octicon-eye-closed-24'
export const MORE = 'octicon-kebab-horizontal-24'
export const RENAME = 'octicon-stack-24'
export const SIZE = 'octicon-typography-24'
export const LOCK = 'octicon-lock-24'
export const COPY = 'octicon-copy-24'
export const SORT = 'octicon-sort-desc-24'
export const CHEVRON_DOWN = 'octicon-chevron-down-24'
export const GRABBER = 'octicon-grabber-24'
export const TRASH = 'octicon-trash-24'
export const PIN = 'octicon-pin-24'
export const WRAP = 'octicon-move-to-end-24'
export const EXPAND = 'octicon-triangle-right-24'
export const SHRINK = 'octicon-triangle-down-24'
export const SUB = 'octicon-arrow-up-left-24'
export const CONFIRM = 'octicon-check-24'
export const CANCEL = 'octicon-x-24'
export const SEARCH = 'octicon-search-24'

export const FIRST  = 'octicon-move-to-start-24'
export const LAST  = 'octicon-move-to-end-24'
export const PREVIOUS  = 'octicon-chevron-left-24'
export const NEXT  = 'octicon-chevron-right-24'

export const ASC  = 'octicon-sort-asc-24'
export const DESC  = 'octicon-sort-desc-24'

export const TILE_ALL_DATA = 'octicon-multi-select-24'
export const ONLY_PARENT_DATA = 'octicon-x-24'
export const FOLD_SUB_DATA = 'octicon-quote-24'
