// https://primer.style/foundations/icons

export const TEXT = 'octicon-file-24'
export const TEXTAREA = 'octicon-file-code-24'
export const NUMBER = 'octicon-list-ordered-24'
export const BOOLEAN = 'octicon-checklist-24'
export const FILE = 'octicon-file-zip-24'
export const IMAGE = 'octicon-image-24'
export const SELECT = 'octicon-single-select-24'
export const MULTISELECT = 'octicon-multi-select-24'
export const CHECKBOX = 'octicon-checkbox-24'
export const DATE = 'octicon-calendar-24'
export const DATETIME = 'octicon-calendar-24'
export const TIME = 'octicon-clock-24'
export const EMAIL = 'octicon-mail-24'
export const URL = 'octicon-link-24'
export const PHONE = 'octicon-device-mobile-24'
export const PASSWORD = 'octicon-passkey-fill-24'

export const CHART = 'octicon-graph-24'
export const LIST = 'octicon-list-unordered-24'
export const CALENDAR = 'octicon-calendar-24'
export const BOARD = 'octicon-project-24'
export const GANTT = 'octicon-workflow-24'


export const ADD = 'octicon-plus-24'
export const EDIT = 'octicon-pencil-24'
export const DELETE = 'octicon-trash-24'
export const MORE = 'octicon-kebab-horizontal-24'
export const OPEN = 'octicon-link-external-24'
export const RENAME = 'octicon-stack-24'
export const SIZE = 'octicon-typography-24'
export const LOCK = 'octicon-lock-24'

